### ISSUE TITLE
Experience Strategy - Marketplace POV

### ISSUE THREAD

**Issue by ezoehunt** [MarketplaceUX/mow#3]
This is where we'll discuss the new POV for Marketplace. 

@punchyfrisky (Sakina) to lead this workstream.

@flekkowich (Rina), @devaneymoz (Scott), and Niran to be part of the team working on this.

Keep me and Phil in the loop as you go, so our designs reflect the POV.

We'd like to get this work completed by Friday Mar 13th (scary!).

**Comment by devaneymoz** [comment]
Cool. 

@ezoehunt: when you say "work completed" by March 13, do you mean just the copy-messaging, or copy integrated with design? 

Should we start by identifying areas on MP where POV messaging will appear? Areas to consider:

1) "About" page. Might include such elements as: 
- Top-of-page, brief statement defining the purpose, function, and POV of Marketplace. 
- Provide path for devs to submit apps (and later MOW's)
- Newsletter sign-up
- Links to Apps Blog and @FirefoxApps Twitter. 

2) Tagline to appear alongside Marketplace logo 

Thoughts? 

I'll get to work on a draft for the philosophy statement and share here for feedback. Once we have it in a presentable state we should bubble up for review amongst Bertrand and DavidA.

**Comment by dbialer** [comment]
What does POV stand for?

**Comment by devaneymoz** [comment]
Point of view

**Comment by ezoehunt** [comment]
Also some more info, in case you don't already have it. 
1) Right now the idea is that "mobile optimized websites" include any format (m.dot, webapp, responsive, etc) that "looks ok" on a phone. The details of what counts as "looks good" are TBD. But for now we know that we're not excluding any format from the Marketplace.
2) The content will be top global sites and top local sites. So a mix.

**Comment by punchyfrisky** [comment]
- Meeting invite sent to team for Tuesday
- In the meantime, here's a Gdoc where we can start jotting down ideas. I've added a framework with lots of thought starters - it seems we don't need (and can't achieve) this level of detail by next week, but we'll probably want to continue delving into this after. Liz, would love for you to weigh in with comments on anything else that you would want the POV to address (or things that aren't relevant at this point). https://docs.google.com/a/mozilla.com/document/d/1_r3Qo-XyQ3B9E6Cvl0HxUC6U_TkXaaFyHxa4hO2wITk/edit?usp=sharing
