### ISSUE TITLE
3 Ways to Contribute to MOW #1

### ISSUE THREAD

**Issue by ezoehunt** [MarketplaceUX/mow#6]
**Sketch (or prototype) your solution to one (or more) of the following interactions.** We've left these purposefully broad/vague so that we don't influence you with our existing ideas. 

When you've completed your work, add a comment here explaining your solution - be sure to upload your sketch or a link to your prototype. Feel free to discuss everybody's solutions, and we'll discuss these on Thursday during our regular design meeting.

As you work on these, keep our customer experience framework in mind:
http://marketplaceux.github.io/mow/concepts/images/MOW_Vision_CX_040215_small.pdf

_note: Home page images are directional and preliminary. We wanted you to have some context for this assignment._

**Have fun!**

<hr>
1. **_Quiz block**_ Here we ask people for an explicit preference for an interest category, for example, Sports. If we get a "yes" answer, we'll provide the person with Sports recommendations.<br/><br/>For this one, we'd like you to think about how this interaction works. Consider what happens when the person selects the "yes" answer and what happens when the person selects the "no" answer.<br/><br/>Look for the row with the yellow block that says "I want more Food & Drink on this page" on this home page:
   http://marketplaceux.github.io/mow/concepts/images/teamwork/mow_home_040215_new.png
2. **_Surprise Me block**_ Here we want to provide unexpected content and/or an unexpected interaction.<br/><br/>For this one, we'd like you to think about how this interaction works and how it delivers unexpected content.<br/><br/>Look for the row with the green block that says "Surprise Me" on this home page:
   http://marketplaceux.github.io/mow/concepts/images/teamwork/mow_home_040215_new.png
3. **_Wild Card!**_ Choose any interaction to sketch or prototype.<br/><br/>Choose any of the interactions shown on the home page listed above.<br/><br/>Or select an interaction from our earlier design improv:
   https://docs.google.com/a/mozilla.com/document/d/1dn7Tl_EhYg-n5YRsgRxqBBpwQ0fruMgOrnLWQdUcX6c

**Comment by clouserw** [comment]
Upon reflection, this might be a little tryhard and makes the UI too heavy, but I already drew it, so why not.  My idea is to let each of the blocks rotate.  The Quiz Block would look like this:

![2015-04-07 09 13 20-1](https://cloud.githubusercontent.com/assets/80098/7027956/8a15f13a-dd07-11e4-875e-5347983b2da1.jpg)

Although I think it should be way more specific than Sports (like, Golf).  If they choose no, it could prompt again ("how about COOKING?") or simply disappear.

If a block disappears I think we should fill in the space, like a giant game of tetris.  A big block disappears, the whole thing could collapse in on the space.  If a half block disappears, we could either slide a halfblock down from above it (if there is one there) or have the remaining half block get squished into a short block that takes up twice the width -- more work there as we'd need two rendering views for all the half blocks.

With the rotation idea the Surprise Me block could have two outcomes (depending which way you rotated it) and you could get a little preview of each before you committed to the full rotation (assuming you couldn't rotate back or that rotating back did something else).

I'm not sure I'm in love with these ideas for an actual interface I'd use, but if we make a whimsy UI sometime it could be a candidate there.

**Comment by ddurst** [comment]
(adds https://docs.google.com/drawings/d/1DYZEBzEGcNHCgeEYfSblwkF7LEMgOVVLjcxKwIQxnDk/edit)

**Comment by clouserw** [comment]
Other ideas:

1) The blocks could rotate or flip after a swipe or long press to reveal settings like "Show me more like this" or "Don't show me this"

2) What if the links like "What's new in Games?" and "Best of Social" just animated a bunch of content into the feed instead of going to another page?  Chuck says this is hard on low end devices, and I'm not thrilled with the idea of not having linkable URLs...

3) Subtle movements on the page are all the rage these days.  I'm thinking of stuff like this: http://www.theverge.com/a/apple-watch-review

**Comment by pwalm** [comment]
Some ideas:
![img_2211](https://cloud.githubusercontent.com/assets/6797635/7072163/0bbc3dd2-de9f-11e4-8db7-acd87c08b6c9.JPG)
![img_2212](https://cloud.githubusercontent.com/assets/6797635/7072168/11235972-de9f-11e4-9ce9-4bb10c4a3448.JPG)
![img_2213](https://cloud.githubusercontent.com/assets/6797635/7072171/13e651dc-de9f-11e4-980d-265844fa04f9.JPG)
